### ISSUE TITLE
Slider for seconds

### ISSUE THREAD

**Issue by vfabregat** [smrsan76/imrc-datetime-picker#11]
Do you accept PRs? I need [this](https://github.com/AllenWooooo/rc-datetime-picker/issues/55) and if you will accept PRs I can sent you one.

**Comment by smrsan76** [comment]
Hi @vfabregat ,
That's OK and all your PRs are appreciated.
Thanks...

**Comment by vfabregat** [comment]
Hello @smrsan76!

We already sent you a PR, did you see it? Do you want to change something there?

Let me know if there incorrect there.
regards!

**Comment by smrsan76** [comment]
Hello @vfabregat 

Sorry about this big delay...

> Let me know if there incorrect there.

No, it seems that there isn't anything wrong with your PR.

In fact, the incorrect thing is this abandoned/deprecated package (not your PR).
Because it's codes are so messy and there are so many succeeded rivals for it.

I have 2 suggestions for you:
1. Fork this repo, work on it, and republish it yourself. (if possible)
2. Use one of the succeeded projects.

One of my favorite react calendars is [`react-modern-calendar-datepicker`](https://github.com/Kiarash-Z/react-modern-calendar-datepicker).

Finally, I should say that it's not my first & last react date/time picker package.
One of my important (and unnecessary) tasks is to solve most of the important problems of this package in the next major version. (If I had time)

Good Luck :+1:

**Comment by smrsan76** [comment]
Hey @vfabregat 

I'm closing this issue, but you are free to open it again and let me know if there were any related issues.

Thanks for your contribution :wink:
